services:
  web:
    build: ./crud_api
    ports:
      - 5001:80
    depends_on:
       - "postgres"
    networks:
        - backnetwork
  postgres:
    image: postgres:alpine
    networks:
        - backnetwork
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    expose:
      - 5432
  front:
    build: ./crud_react
    ports:
      - 3001:3000
    networks:
        - backnetwork
    depends_on:
       - "web"

networks:
  backnetwork:
    name: backnetwork
    driver: bridge